/**
 * Schemas de Swagger/OpenAPI para documentación
 */

export const swaggerSchemas = {
  Tour: {
    type: "object",
    properties: {
      id: { type: "string" },
      slug: { type: "string" },
      name: { type: "string" },
      subtitle: { type: "string", nullable: true },
      category: { type: "string" },
      difficulty: { type: "string" },
      durationHours: { type: "number" },
      featuredImage: { type: "string" },
      heroImage: { type: "string" },
      shortDescription: { type: "string" },
      longDescription: { type: "string" },
      restrictionText: { type: "string" },
      isActive: { type: "boolean" },
      prices: {
        type: "array",
        items: { $ref: "#/components/schemas/TourPrice" },
      },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  TourPrice: {
    type: "object",
    properties: {
      id: { type: "string" },
      tourId: { type: "string" },
      currency: { type: "string", example: "ARS" },
      priceAdult: { type: "number", example: 100000 },
      priceChild: { type: "number", example: 50000 },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateTourInput: {
    type: "object",
    required: [
      "slug",
      "name",
      "category",
      "difficulty",
      "durationHours",
      "featuredImage",
      "heroImage",
      "shortDescription",
      "longDescription",
    ],
    properties: {
      slug: { type: "string", example: "tour-ushuaia" },
      name: { type: "string", example: "Tour Ushuaia" },
      subtitle: { type: "string", example: "Descubre Ushuaia" },
      category: { type: "string", example: "summer" },
      difficulty: { type: "string", example: "Baja" },
      durationHours: { type: "number", example: 4 },
      featuredImage: { type: "string", example: "/images/tour.jpg" },
      heroImage: { type: "string", example: "/images/tour-hero.jpg" },
      shortDescription: { type: "string" },
      longDescription: { type: "string" },
      restrictionText: { type: "string" },
      isActive: { type: "boolean", default: true },
    },
  },
  CreateTourPriceInput: {
    type: "object",
    required: ["tourId", "currency", "priceAdult", "priceChild"],
    properties: {
      tourId: { type: "string" },
      currency: { type: "string", example: "ARS" },
      priceAdult: { type: "number", example: 100000 },
      priceChild: { type: "number", example: 50000 },
    },
  },
  Order: {
    type: "object",
    properties: {
      id: { type: "string" },
      code: { type: "string" },
      type: { type: "string", enum: ["RESERVATION", "ENQUIRY"] },
      status: {
        type: "string",
        enum: ["PENDING_PAYMENT", "PAID", "CANCELLED", "EXPIRED", "COMPLETED"],
      },
      customerName: { type: "string" },
      customerEmail: { type: "string" },
      customerPhone: { type: "string" },
      currency: { type: "string" },
      totalAmount: { type: "number" },
      expiresAt: { type: "string", format: "date-time", nullable: true },
      notes: { type: "string", nullable: true },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateOrderInput: {
    type: "object",
    required: [
      "tourId",
      "departureId",
      "numAdults",
      "numChildren",
      "currency",
      "customerName",
      "customerEmail",
      "customerPhone",
      "passengers",
    ],
    properties: {
      tourId: { type: "string" },
      departureId: { type: "string" },
      numAdults: { type: "number", minimum: 1 },
      numChildren: { type: "number", minimum: 0 },
      currency: { type: "string", example: "ARS" },
      customerName: { type: "string" },
      customerEmail: { type: "string", format: "email" },
      customerPhone: { type: "string" },
      passengers: {
        type: "array",
        items: {
          type: "object",
          properties: {
            type: { type: "string", enum: ["ADULT", "CHILD", "INFANT"] },
            firstName: { type: "string" },
            lastName: { type: "string" },
            birthDate: { type: "string", format: "date" },
            documentType: { type: "string" },
            documentNumber: { type: "string" },
            nationality: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string" },
          },
        },
      },
      notes: { type: "string" },
    },
  },
  Availability: {
    type: "object",
    properties: {
      id: { type: "string" },
      date: { type: "string", format: "date" },
      startTime: { type: "string", example: "09:00" },
      endTime: { type: "string", example: "13:00", nullable: true },
      available: { type: "number" },
      seatsTotal: { type: "number" },
      seatsHeld: { type: "number" },
      seatsConfirmed: { type: "number" },
      isActive: { type: "boolean" },
    },
  },
};

