-- AlterTable
ALTER TABLE "Tour" ADD COLUMN "mondayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "tuesdayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "wednesdayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "thursdayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "fridayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "saturdayAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "sundayAvailable" BOOLEAN NOT NULL DEFAULT true;

